# Generated by Django 5.2 on 2025-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('pasos', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Minutos')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
